// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: github/v1/github.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Github_GetHealth_FullMethodName           = "/api.github.v1.Github/GetHealth"
	Github_GetPRMetrics_FullMethodName        = "/api.github.v1.Github/GetPRMetrics"
	Github_GetMonthlyStats_FullMethodName     = "/api.github.v1.Github/GetMonthlyStats"
	Github_GetRepoStats_FullMethodName        = "/api.github.v1.Github/GetRepoStats"
	Github_GetContributorStats_FullMethodName = "/api.github.v1.Github/GetContributorStats"
	Github_GetIssueStats_FullMethodName       = "/api.github.v1.Github/GetIssueStats"
	Github_GetDetailedPRStats_FullMethodName  = "/api.github.v1.Github/GetDetailedPRStats"
)

// GithubClient is the client API for Github service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Github service for repository metrics
type GithubClient interface {
	// Get health status
	GetHealth(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*HealthResponse, error)
	// Get PR metrics for a repository
	GetPRMetrics(ctx context.Context, in *RepositoryRequest, opts ...grpc.CallOption) (*PRMetricsResponse, error)
	// Get monthly statistics for a repository
	GetMonthlyStats(ctx context.Context, in *RepositoryRequest, opts ...grpc.CallOption) (*MonthlyStatsResponse, error)
	// Get repository statistics
	GetRepoStats(ctx context.Context, in *RepositoryRequest, opts ...grpc.CallOption) (*RepoStatsResponse, error)
	// Get contributor statistics
	GetContributorStats(ctx context.Context, in *RepositoryRequest, opts ...grpc.CallOption) (*ContributorStatsResponse, error)
	// Get issue statistics
	GetIssueStats(ctx context.Context, in *RepositoryRequest, opts ...grpc.CallOption) (*IssueStatsResponse, error)
	// Get detailed PR statistics
	GetDetailedPRStats(ctx context.Context, in *RepositoryRequest, opts ...grpc.CallOption) (*DetailedPRStatsResponse, error)
}

type githubClient struct {
	cc grpc.ClientConnInterface
}

func NewGithubClient(cc grpc.ClientConnInterface) GithubClient {
	return &githubClient{cc}
}

func (c *githubClient) GetHealth(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, Github_GetHealth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *githubClient) GetPRMetrics(ctx context.Context, in *RepositoryRequest, opts ...grpc.CallOption) (*PRMetricsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PRMetricsResponse)
	err := c.cc.Invoke(ctx, Github_GetPRMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *githubClient) GetMonthlyStats(ctx context.Context, in *RepositoryRequest, opts ...grpc.CallOption) (*MonthlyStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MonthlyStatsResponse)
	err := c.cc.Invoke(ctx, Github_GetMonthlyStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *githubClient) GetRepoStats(ctx context.Context, in *RepositoryRequest, opts ...grpc.CallOption) (*RepoStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RepoStatsResponse)
	err := c.cc.Invoke(ctx, Github_GetRepoStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *githubClient) GetContributorStats(ctx context.Context, in *RepositoryRequest, opts ...grpc.CallOption) (*ContributorStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ContributorStatsResponse)
	err := c.cc.Invoke(ctx, Github_GetContributorStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *githubClient) GetIssueStats(ctx context.Context, in *RepositoryRequest, opts ...grpc.CallOption) (*IssueStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IssueStatsResponse)
	err := c.cc.Invoke(ctx, Github_GetIssueStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *githubClient) GetDetailedPRStats(ctx context.Context, in *RepositoryRequest, opts ...grpc.CallOption) (*DetailedPRStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DetailedPRStatsResponse)
	err := c.cc.Invoke(ctx, Github_GetDetailedPRStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GithubServer is the server API for Github service.
// All implementations must embed UnimplementedGithubServer
// for forward compatibility.
//
// Github service for repository metrics
type GithubServer interface {
	// Get health status
	GetHealth(context.Context, *emptypb.Empty) (*HealthResponse, error)
	// Get PR metrics for a repository
	GetPRMetrics(context.Context, *RepositoryRequest) (*PRMetricsResponse, error)
	// Get monthly statistics for a repository
	GetMonthlyStats(context.Context, *RepositoryRequest) (*MonthlyStatsResponse, error)
	// Get repository statistics
	GetRepoStats(context.Context, *RepositoryRequest) (*RepoStatsResponse, error)
	// Get contributor statistics
	GetContributorStats(context.Context, *RepositoryRequest) (*ContributorStatsResponse, error)
	// Get issue statistics
	GetIssueStats(context.Context, *RepositoryRequest) (*IssueStatsResponse, error)
	// Get detailed PR statistics
	GetDetailedPRStats(context.Context, *RepositoryRequest) (*DetailedPRStatsResponse, error)
	mustEmbedUnimplementedGithubServer()
}

// UnimplementedGithubServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGithubServer struct{}

func (UnimplementedGithubServer) GetHealth(context.Context, *emptypb.Empty) (*HealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHealth not implemented")
}
func (UnimplementedGithubServer) GetPRMetrics(context.Context, *RepositoryRequest) (*PRMetricsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPRMetrics not implemented")
}
func (UnimplementedGithubServer) GetMonthlyStats(context.Context, *RepositoryRequest) (*MonthlyStatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMonthlyStats not implemented")
}
func (UnimplementedGithubServer) GetRepoStats(context.Context, *RepositoryRequest) (*RepoStatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRepoStats not implemented")
}
func (UnimplementedGithubServer) GetContributorStats(context.Context, *RepositoryRequest) (*ContributorStatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetContributorStats not implemented")
}
func (UnimplementedGithubServer) GetIssueStats(context.Context, *RepositoryRequest) (*IssueStatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetIssueStats not implemented")
}
func (UnimplementedGithubServer) GetDetailedPRStats(context.Context, *RepositoryRequest) (*DetailedPRStatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDetailedPRStats not implemented")
}
func (UnimplementedGithubServer) mustEmbedUnimplementedGithubServer() {}
func (UnimplementedGithubServer) testEmbeddedByValue()                {}

// UnsafeGithubServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GithubServer will
// result in compilation errors.
type UnsafeGithubServer interface {
	mustEmbedUnimplementedGithubServer()
}

func RegisterGithubServer(s grpc.ServiceRegistrar, srv GithubServer) {
	// If the following call pancis, it indicates UnimplementedGithubServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Github_ServiceDesc, srv)
}

func _Github_GetHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GithubServer).GetHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Github_GetHealth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GithubServer).GetHealth(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Github_GetPRMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RepositoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GithubServer).GetPRMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Github_GetPRMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GithubServer).GetPRMetrics(ctx, req.(*RepositoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Github_GetMonthlyStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RepositoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GithubServer).GetMonthlyStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Github_GetMonthlyStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GithubServer).GetMonthlyStats(ctx, req.(*RepositoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Github_GetRepoStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RepositoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GithubServer).GetRepoStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Github_GetRepoStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GithubServer).GetRepoStats(ctx, req.(*RepositoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Github_GetContributorStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RepositoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GithubServer).GetContributorStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Github_GetContributorStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GithubServer).GetContributorStats(ctx, req.(*RepositoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Github_GetIssueStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RepositoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GithubServer).GetIssueStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Github_GetIssueStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GithubServer).GetIssueStats(ctx, req.(*RepositoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Github_GetDetailedPRStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RepositoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GithubServer).GetDetailedPRStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Github_GetDetailedPRStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GithubServer).GetDetailedPRStats(ctx, req.(*RepositoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Github_ServiceDesc is the grpc.ServiceDesc for Github service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Github_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.github.v1.Github",
	HandlerType: (*GithubServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetHealth",
			Handler:    _Github_GetHealth_Handler,
		},
		{
			MethodName: "GetPRMetrics",
			Handler:    _Github_GetPRMetrics_Handler,
		},
		{
			MethodName: "GetMonthlyStats",
			Handler:    _Github_GetMonthlyStats_Handler,
		},
		{
			MethodName: "GetRepoStats",
			Handler:    _Github_GetRepoStats_Handler,
		},
		{
			MethodName: "GetContributorStats",
			Handler:    _Github_GetContributorStats_Handler,
		},
		{
			MethodName: "GetIssueStats",
			Handler:    _Github_GetIssueStats_Handler,
		},
		{
			MethodName: "GetDetailedPRStats",
			Handler:    _Github_GetDetailedPRStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github/v1/github.proto",
}
