// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: github/v1/luminex.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_github_v1_luminex_proto protoreflect.FileDescriptor

const file_github_v1_luminex_proto_rawDesc = "" +
	"\n" +
	"\x17github/v1/luminex.proto\x12\rapi.github.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x16github/v1/github.proto2\xf5\x04\n" +
	"\aLuminex\x12D\n" +
	"\tGetHealth\x12\x16.google.protobuf.Empty\x1a\x1d.api.github.v1.HealthResponse\"\x00\x12T\n" +
	"\fGetPRMetrics\x12 .api.github.v1.RepositoryRequest\x1a .api.github.v1.PRMetricsResponse\"\x00\x12Z\n" +
	"\x0fGetMonthlyStats\x12 .api.github.v1.RepositoryRequest\x1a#.api.github.v1.MonthlyStatsResponse\"\x00\x12T\n" +
	"\fGetRepoStats\x12 .api.github.v1.RepositoryRequest\x1a .api.github.v1.RepoStatsResponse\"\x00\x12b\n" +
	"\x13GetContributorStats\x12 .api.github.v1.RepositoryRequest\x1a'.api.github.v1.ContributorStatsResponse\"\x00\x12V\n" +
	"\rGetIssueStats\x12 .api.github.v1.RepositoryRequest\x1a!.api.github.v1.IssueStatsResponse\"\x00\x12`\n" +
	"\x12GetDetailedPRStats\x12 .api.github.v1.RepositoryRequest\x1a&.api.github.v1.DetailedPRStatsResponse\"\x00B,Z*github-insights-dashboard/api/github/v1;v1b\x06proto3"

var file_github_v1_luminex_proto_goTypes = []any{
	(*emptypb.Empty)(nil),            // 0: google.protobuf.Empty
	(*RepositoryRequest)(nil),        // 1: api.github.v1.RepositoryRequest
	(*HealthResponse)(nil),           // 2: api.github.v1.HealthResponse
	(*PRMetricsResponse)(nil),        // 3: api.github.v1.PRMetricsResponse
	(*MonthlyStatsResponse)(nil),     // 4: api.github.v1.MonthlyStatsResponse
	(*RepoStatsResponse)(nil),        // 5: api.github.v1.RepoStatsResponse
	(*ContributorStatsResponse)(nil), // 6: api.github.v1.ContributorStatsResponse
	(*IssueStatsResponse)(nil),       // 7: api.github.v1.IssueStatsResponse
	(*DetailedPRStatsResponse)(nil),  // 8: api.github.v1.DetailedPRStatsResponse
}
var file_github_v1_luminex_proto_depIdxs = []int32{
	0, // 0: api.github.v1.Luminex.GetHealth:input_type -> google.protobuf.Empty
	1, // 1: api.github.v1.Luminex.GetPRMetrics:input_type -> api.github.v1.RepositoryRequest
	1, // 2: api.github.v1.Luminex.GetMonthlyStats:input_type -> api.github.v1.RepositoryRequest
	1, // 3: api.github.v1.Luminex.GetRepoStats:input_type -> api.github.v1.RepositoryRequest
	1, // 4: api.github.v1.Luminex.GetContributorStats:input_type -> api.github.v1.RepositoryRequest
	1, // 5: api.github.v1.Luminex.GetIssueStats:input_type -> api.github.v1.RepositoryRequest
	1, // 6: api.github.v1.Luminex.GetDetailedPRStats:input_type -> api.github.v1.RepositoryRequest
	2, // 7: api.github.v1.Luminex.GetHealth:output_type -> api.github.v1.HealthResponse
	3, // 8: api.github.v1.Luminex.GetPRMetrics:output_type -> api.github.v1.PRMetricsResponse
	4, // 9: api.github.v1.Luminex.GetMonthlyStats:output_type -> api.github.v1.MonthlyStatsResponse
	5, // 10: api.github.v1.Luminex.GetRepoStats:output_type -> api.github.v1.RepoStatsResponse
	6, // 11: api.github.v1.Luminex.GetContributorStats:output_type -> api.github.v1.ContributorStatsResponse
	7, // 12: api.github.v1.Luminex.GetIssueStats:output_type -> api.github.v1.IssueStatsResponse
	8, // 13: api.github.v1.Luminex.GetDetailedPRStats:output_type -> api.github.v1.DetailedPRStatsResponse
	7, // [7:14] is the sub-list for method output_type
	0, // [0:7] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_github_v1_luminex_proto_init() }
func file_github_v1_luminex_proto_init() {
	if File_github_v1_luminex_proto != nil {
		return
	}
	file_github_v1_github_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_v1_luminex_proto_rawDesc), len(file_github_v1_luminex_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_github_v1_luminex_proto_goTypes,
		DependencyIndexes: file_github_v1_luminex_proto_depIdxs,
	}.Build()
	File_github_v1_luminex_proto = out.File
	file_github_v1_luminex_proto_goTypes = nil
	file_github_v1_luminex_proto_depIdxs = nil
}
